# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_commentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='review',
            field=models.CharField(default=2, max_length=300),
            preserve_default=False,
        ),
    ]
